### ISSUE TITLE
Kotlin incident is not triggered for non-text content

### ISSUE THREAD

**Issue by madhead** [JavaBy/jprof_by_bot#12]
An update like this:

```json
{
   "update_id":550799694,
   "message":{
      "message_id":82547,
      "from":{
         "id":42,
         "is_bot":false,
         "first_name":"X",
         "last_name":"Y",
         "username":"Z"
      },
      "chat":{
         "id":-42,
         "title":"JPROF.BY",
         "username":"jprof_by",
         "type":"supergroup"
      },
      "date":1625571795,
      "video":{
         "duration":3,
         "width":464,
         "height":848,
         "file_name":"video.mp4",
         "mime_type":"video/mp4",
         "thumb":{
"file_id":"AAyAE",
            "file_unique_id":"AQUty",
            "file_size":12905,
            "width":175,
            "height":320
         },
         "file_id":"BAgBA",
         "file_unique_id":"AgKUs",
         "file_size":572314
      },
      "caption":"\u0415\u0441\u043b\u0438 \u0447\u0442\u043e \u0438\u0449\u0435\u043c \u043b\u044e\u0434\u0435\u0439 \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0443, \u0442\u043e\u043b\u044c\u043a\u043e \u0442\u0443\u0442 \u041a\u043e\u0442\u043b\u0438\u043d \u0435\u0441\u043b\u0438 \u0447\u0442\u043e :D"
   }
}
```

Because of this `where` clause, where only the `TextContent` is processed:

https://github.com/JavaBy/jprof_by_bot/blob/35d980af88210c065d128da4aea67af21687fe34/kotlin/src/main/kotlin/by/jprof/telegram/bot/kotlin/KotlinMentionsUpdateProcessor.kt#L40-L43

Types of content that should be supported as well:

- [ ] `Texted` / `TextedInput` subclasses
- [ ] `PollContent.poll` (question, answers)
- [ ] `DocumentContent.text`
- [ ] `GameContent.game` (title, description, text)
- [ ] `InvoiceContent.invoice` (title, description)
- [ ] `PhotoContent.text`
- [ ] `VenueContent.venue` (title)
- [ ] `VideoContent.text`

**Comment by wtsiamruk** [comment]
@madhead here we want to change unicode based string (the caption) to the regular one and then apply pattern search, correct?

**Comment by madhead** [comment]
@wtsiamruk, yes, this `when` clause has to been expanded to support more `MessageContent` subclasses.

**Comment by madhead** [comment]
It has nothing to do with Unicode, it's just a a weird way the JSON was logged. In Kotlin code that caption from the message above would be "Если что ищем людей в команду, только тут Котлин если что :D"
