### ISSUE TITLE
JProf Digest

### ISSUE THREAD

**Issue by madhead** [JavaBy/jprof_by_bot#19]
Related to #7 and #18, but kinda different.

Once per week, generate a digest:

- Posted links
- Topic discussed
- Friday's poll results
- Top messages (by number of replies)
- ???

**Comment by dhruvnagarajan** [comment]
Hi @madhead could you explain a bit more about the repo in readme? What does the bot do?

**Comment by madhead** [comment]
Hi, @dhruvnagarajan!

Thank you for your interest. I've added some docks, check them out!
